version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: fitwise-postgres
    environment:
      POSTGRES_DB: fitwise_db
      POSTGRES_USER: admin_postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
